export interface MenuItem {
  name: string;
  description: string;
  price: string;
}

export const menuData = {
  en: {
    "Coffee": [
      { name: "Espresso (Single | Double)", description: "", price: "€3.00 | €4.00" },
      { name: "Freddo Espresso (Single | Double)", description: "", price: "€4.00 | €5.00" },
      { name: "Cappuccino (Single | Double)", description: "", price: "€4.00 | €5.00" },
      { name: "Freddo Cappuccino (Single | Double)", description: "", price: "€4.00 | €5.00" },
      { name: "Freddo Cappuccino (Caramel or Strawberry)", description: "", price: "€4.00" },
      { name: "Greek coffee (Single | Double)", description: "", price: "€2.50 | €3.50" },
      { name: "Americano", description: "", price: "€4.00" },
      { name: "Lungo", description: "", price: "€4.00" },
      { name: "Latte", description: "", price: "€4.50" },
      { name: "Frappe | Nes", description: "", price: "€4.00" },
      { name: "Frappe (with ice cream)", description: "", price: "€5.00" },
      { name: "Filter Coffee", description: "", price: "€4.00" },
    ],
    "Beverages": [
      { name: "Bottled Water", description: "", price: "€1.00" },
      { name: "Sparkling Water", description: "", price: "€3.50" },
      { name: "Soda", description: "", price: "€3.00" },
      { name: "Tonik Water", description: "", price: "€3.00" },
      { name: "Coca - Cola Light | Zero | Stevia", description: "", price: "€3.00" },
      { name: "Orange Juice | Lemonade | Sprite", description: "", price: "€3.00" },
      { name: "Loux Orange Juice | Cherry", description: "", price: "€3.00" },
      { name: "Fresh Orange Juice", description: "", price: "€4.00" },
      { name: "Mixed Fresh Juice", description: "", price: "€5.00" },
      { name: "Homemade Lemonade | Ginger", description: "", price: "€4.00" },
      { name: "B-Fresh Homemade (sugar free)", description: "", price: "€4.50" },
      { name: "Ice Tea Peach | Lemon | Pomegranate", description: "", price: "€3.50" },
      { name: "Arizona Tea Pomegranate | Green | Honey", description: "", price: "€4.00" },
      { name: "Amita", description: "", price: "€3.50" },
      { name: "Schweppes", description: "", price: "€3.50" },
      { name: "Tea", description: "", price: "€3.50" },
      { name: "Milk Shake", description: "", price: "€5.00" },
      { name: "Drinking Chocolate (hot/cold)", description: "", price: "€4.00" },
      { name: "Granita (Strawberry, Chocolate)", description: "", price: "€4.00" },
      { name: "Monster", description: "", price: "€3.50" },
      { name: "Red Bull", description: "", price: "€4.50" },
    ],
    "Breakfast": [
      { name: "Omelette", description: "A classic, fluffy omelette, cooked to perfection.", price: "€5.00" },
      { name: "Omelette Special", description: "Loaded with gouda cheese, savory bacon, fresh tomato, and pepper.", price: "€7.00" },
      { name: "Country-Style Omelette", description: "A hearty mix of feta cheese, local sausage, tomato, and pepper.", price: "€7.50" },
      { name: "Pancakes (Breakfast)", description: "Warm pancakes layered with cheese, bacon, creamy mayonnaise, and tomato.", price: "€6.50" },
    ],
    "Snacks": [
      { name: "Toast (Cheese, Ham or Turkey)", description: "A classic toasted sandwich with your choice of filling.", price: "€4.00" },
      { name: "Savory Crepe with Gouda", description: "A warm crepe filled with melted Gouda cheese. Add your favorite ingredients.", price: "€4.50" },
      { name: "Club Sandwich", description: "Layers of cheese, ham, tomato, bacon, and lettuce in a triple-decker sandwich.", price: "€8.00" },
      { name: "Chicken Club Sandwich", description: "A delicious club sandwich with tender chicken, cheese, tomato, and lettuce.", price: "€9.00" },
      { name: "Cheeseburger", description: "A juicy beef burger topped with melted cheese and our special sauce.", price: "€9.00" },
      { name: "Chicken Burger", description: "A crispy chicken burger with cheese, fresh tomato, lettuce, and a tangy mustard sauce.", price: "€9.00" },
      { name: "Burger with Caramelized Onion", description: "A gourmet beef burger with sweet caramelized onions, tomato, and lettuce.", price: "€9.50" },
    ],
    "Salads": [
      { name: "Greek Traditional Salad", description: "The classic Greek salad with tomato, cucumber, onion, olives, pepper, and feta cheese.", price: "€8.50" },
      { name: "Caesar's Salad", description: "Crisp green vegetables, bacon, croutons, and tender chicken with a creamy Caesar's dressing.", price: "€9.00" },
      { name: "Rocket Salad", description: "Peppery rocket leaves tossed with parmesan cheese and a simple balsamic sauce.", price: "€9.00" },
      { name: "Soleto Salad", description: "Our signature salad with fresh greens, sweet orange, raisins, walnuts, parmesan, and a balsamic cream drizzle.", price: "€9.00" },
    ],
    "Appetizers": [
      { name: "Feta Cheese", description: "A classic slice of Greek feta, drizzled with olive oil and oregano.", price: "€4.50" },
      { name: "Spicy Cheese Salad", description: "A creamy and tangy cheese spread with a spicy kick.", price: "€5.00" },
      { name: "Greek Saganaki", description: "Pan-fried Greek cheese with a golden crust and a warm, melted center.", price: "€5.50" },
      { name: "Talagani", description: "Grilled Talagani cheese, soft and milky with a distinctive flavor.", price: "€6.00" },
      { name: "Feta with Honey", description: "Baked feta cheese drizzled with honey and sprinkled with sesame seeds.", price: "€6.50" },
      { name: "French Fries", description: "Crispy, golden fries, perfectly salted.", price: "€4.00" },
      { name: "Marinated Anchovy", description: "Delicate anchovy fillets marinated in olive oil and herbs.", price: "€8.00" },
      { name: "Fried Anchovy", description: "Crispy fried anchovies, a perfect seaside snack.", price: "€8.50" },
      { name: "Fried Calamari", description: "Tender calamari, served with lemon aioli and arugula", price: "€10.00" },
    ],
    "Pizza": [
      { name: "Pizza Margarita", description: "The timeless classic with rich tomato sauce and melted gouda cheese.", price: "€9.50" },
      { name: "Pizza Ham", description: "A savory pizza with tomato sauce, ham, and gouda cheese.", price: "€11.00" },
      { name: "Pizza Pepperone", description: "A spicy favorite with tomato sauce, pepperoni, and gouda cheese.", price: "€12.00" },
      { name: "Pizza Classic", description: "A flavorful combination of tomato sauce, bacon, ham, and gouda cheese.", price: "€12.00" },
      { name: "Pizza Greek", description: "A taste of Greece with tomato sauce, gouda, olives, pepper, fresh tomato, onion, and feta.", price: "€13.00" },
      { name: "Pizza Special", description: "Fully loaded with tomato sauce, bacon, ham, gouda cheese, pepper, and mushrooms.", price: "€13.00" },
    ],
    "Pasta": [
      { name: "Pomodoro", description: "Simple and delicious with a rich tomato sauce, fresh basil, and Kefalotiri cheese.", price: "€8.50" },
      { name: "Carbonara", description: "A creamy classic with bacon, light cream, and parmesan cheese.", price: "€9.50" },
      { name: "Baked Pasta", description: "Oven-baked pasta with gouda cheese, ham, bacon, tomato sauce, and basil.", price: "€9.50" },
      { name: "Pennes All Freddo with Chicken", description: "Penne pasta in a creamy sauce with chicken, parmesan, and a touch of sour cream.", price: "€10.00" },
    ],
    "Grill": [
      { name: "Sausage", description: "Flavorful grilled local sausage.", price: "€7.50" },
      { name: "Pancetta", description: "Slices of savory pancetta, grilled to perfection.", price: "€9.50" },
      { name: "Chicken Fillet", description: "A tender and lean grilled chicken fillet.", price: "€10.50" },
      { name: "Beef Burger with French Fries", description: "A classic beef burger patty served with a side of crispy french fries.", price: "€10.50" },
      { name: "Pork Chops with French Fries", description: "Juicy, grilled pork chops served with a generous portion of french fries.", price: "€12.00" },
      { name: "Mix Grill (for 2 people)", description: "A generous platter with steak, beef burger, chicken, sausage, pancetta, french fries, and pitta bread.", price: "€29.50" },
      { name: "Mix Grill (for 4 people)", description: "An even bigger platter for sharing with friends and family.", price: "€39.50" },
      { name: "Fish Plate (for 2 people)", description: "A delightful assortment of fried anchovy, cod, marinated anchovy, shrimps, squid, and octopus.", price: "€35.00" },
      { name: "Fish Plate (for 4 people)", description: "A feast from the sea, perfect for sharing.", price: "€50.00" },
    ],
    "Sweets": [
      { name: "IceCream scoop", description: "A scoop of your favorite ice cream, topped with sweet syrup.", price: "€2.50" },
      { name: "Fruit Salad", description: "A refreshing mix of seasonal fresh fruits.", price: "€8.00" },
      { name: "Yogurt with Honey and Walnut", description: "Creamy Greek yogurt topped with golden honey and crunchy walnuts.", price: "€5.00" },
      { name: "Chocolate Crepe", description: "A delicate crepe filled with luscious chocolate. Ask to add your favorite toppings.", price: "€4.50" },
      { name: "Waffle with Chocolate", description: "A warm, crisp waffle drizzled with rich chocolate sauce. Add a scoop of ice cream for the perfect treat.", price: "€5.00" },
      { name: "Pancakes with Praline | Bueno | Honey", description: "Fluffy pancakes served with your choice of rich praline, creamy Bueno, or sweet honey.", price: "€5.00" },
    ],
    "Wines": [
      { name: "White House Wine Glass", description: "", price: "€3.50" },
      { name: "White House Wine 500ml", description: "", price: "€6.00" },
      { name: "Red House Wine Glass", description: "", price: "€3.50" },
      { name: "Red House Wine 500ml", description: "", price: "€6.00" },
      { name: "Bottled Wine Individual", description: "", price: "€4.00" },
      { name: "Roditis Tetramythos Nature", description: "", price: "€15.00" },
      { name: "Malagouzia Tetramythos Nature", description: "", price: "€19.00" },
      { name: "Kintonis Checkmate Semi Sweet White", description: "", price: "€14.00" },
      { name: "Agiorgitiko Tetramythos Nature", description: "", price: "€17.00" },
    ],
    "Alcohol and beers": [
      { name: "ALFA | ALFA FREE", description: "", price: "€4.00" },
      { name: "BEER ALFA 330ml", description: "", price: "€4.00" },
      { name: "BEER ALFA 500ml", description: "", price: "€4.50" },
      { name: "AMSTEL", description: "", price: "€4.00" },
      { name: "FIX", description: "", price: "€4.00" },
      { name: "MAMMOS", description: "", price: "€4.00" },
      { name: "HEINEKEN", description: "", price: "€4.50" },
      { name: "FISCHER", description: "", price: "€4.50" },
      { name: "KAIZER", description: "", price: "€4.50" },
      { name: "SOL", description: "", price: "€4.50" },
      { name: "RADLER", description: "", price: "€4.50" },
      { name: "APPLE CIDER", description: "", price: "€4.50" },
      { name: "Ouzo | Tsipouro Meze (fish | meat)", description: "", price: "€5.00" },
      { name: "Ouzo | Tsipouro bottled 50ml with Meze", description: "", price: "€5.50" },
      { name: "Ouzo 250ml", description: "", price: "€7.50" },
      { name: "Tsipouro 250ml", description: "", price: "€7.00" },
      { name: "VODKA", description: "", price: "€6.50" },
      { name: "GIN", description: "", price: "€6.50" },
      { name: "TEQUILA", description: "", price: "€6.50" },
      { name: "BACARDI", description: "", price: "€6.50" },
      { name: "MALIBU", description: "", price: "€8.00" },
      { name: "SCOTCH", description: "", price: "€6.50" },
      { name: "SPECIAL SCOTCH", description: "", price: "€8.00" },
      { name: "CAMPARI", description: "", price: "€6.50" },
      { name: "APEROL", description: "", price: "€7.00" },
      { name: "MARTINI", description: "", price: "€6.50" },
      { name: "MOJITO", description: "", price: "€6.50" },
      { name: "SANGRIA", description: "", price: "€6.00" },
      { name: "MOSCATO D'ASTI", description: "", price: "€6.00" },
      { name: "GORDON'S SPACE", description: "", price: "€5.00" },
      { name: "BACARDI BREEZER (watermelon | lemon)", description: "", price: "€3.00" },
      { name: "MASTIC LIQUEUR (shot)", description: "", price: "€8.00" },
    ],
  },
  el: {
    "Coffee": [
      { name: "Espresso (Μονός | Διπλός)", description: "", price: "€3.00 | €4.00" },
      { name: "Freddo Espresso (Μονός | Διπλός)", description: "", price: "€4.00 | €5.00" },
      { name: "Cappuccino (Μονός | Διπλός)", description: "", price: "€4.00 | €5.00" },
      { name: "Freddo Cappuccino (Μονός | Διπλός)", description: "", price: "€4.00 | €5.00" },
      { name: "Freddo Cappuccino (Καραμέλα ή Φράουλα)", description: "", price: "€4.00" },
      { name: "Ελληνικός (Μονός | Διπλός)", description: "", price: "€2.50 | €3.50" },
      { name: "Americano", description: "", price: "€4.00" },
      { name: "Lungo", description: "", price: "€4.00" },
      { name: "Latte", description: "", price: "€4.50" },
      { name: "Frappe | Nes", description: "", price: "€4.00" },
      { name: "Frappe (με παγωτό)", description: "", price: "€5.00" },
      { name: "Γαλλικός", description: "", price: "€4.00" },
    ],
    "Beverages": [
      { name: "Εμφιαλωμένο Νερό", description: "", price: "€1.00" },
      { name: "Ανθρακούχο Νερό", description: "", price: "€3.50" },
      { name: "Σόδα", description: "", price: "€3.00" },
      { name: "Tonik Water", description: "", price: "€3.00" },
      { name: "Coca - Cola Light | Zero | Stevia", description: "", price: "€3.00" },
      { name: "Χυμός Πορτοκάλι | Λεμονάδα | Sprite", description: "", price: "€3.00" },
      { name: "Λουξ Πορτοκαλάδα | Βυσσινάδα", description: "", price: "€3.00" },
      { name: "Φυσικός Χυμός Πορτοκάλι", description: "", price: "€4.00" },
      { name: "Ανάμεικτος Φυσικός Χυμός", description: "", price: "€5.00" },
      { name: "Σπιτική Λεμονάδα | Τζίντζερ", description: "", price: "€4.00" },
      { name: "B-Fresh Σπιτικό (χωρίς ζάχαρη)", description: "", price: "€4.50" },
      { name: "Ice Tea Ροδάκινο | Λεμόνι | Ρόδι", description: "", price: "€3.50" },
      { name: "Arizona Tea Pomegranate | Green | Honey", description: "", price: "€4.00" },
      { name: "Amita", description: "", price: "€3.50" },
      { name: "Schweppes", description: "", price: "€3.50" },
      { name: "Τσάι", description: "", price: "€3.50" },
      { name: "Milk Shake", description: "", price: "€5.00" },
      { name: "Σοκολάτα Ρόφημα (ζεστή/κρύα)", description: "", price: "€4.00" },
      { name: "Γρανίτα (Φράουλα, Σοκολάτα)", description: "", price: "€4.00" },
      { name: "Monster", description: "", price: "€3.50" },
      { name: "Red Bull", description: "", price: "€4.50" },
    ],
    "Breakfast": [
      { name: "Ομελέτα", description: "Κλασική, αφράτη ομελέτα, ψημένη στην εντέλεια.", price: "€5.00" },
      { name: "Ομελέτα Σπέσιαλ", description: "Με τυρί γκούντα, μπέικον, φρέσκια ντομάτα και πιπεριά.", price: "€7.00" },
      { name: "Χωριάτικη Ομελέτα", description: "Πλούσια ομελέτα με φέτα, χωριάτικο λουκάνικο, ντομάτα και πιπεριά.", price: "€7.50" },
      { name: "Pancakes (Πρωινό)", description: "Ζεστά pancakes με τυρί, μπέικον, μαγιονέζα και ντομάτα.", price: "€6.50" },
    ],
    "Snacks": [
      { name: "Τοστ (Τυρί, Ζαμπόν ή Γαλοπούλα)", description: "Κλασικό τοστ με επιλογή υλικών.", price: "€4.00" },
      { name: "Αλμυρή Κρέπα με Γκούντα", description: "Κρέπα με λιωμένο τυρί γκούντα. Προσθέστε τα υλικά της αρεσκείας σας.", price: "€4.50" },
      { name: "Club Sandwich", description: "Με τυρί, ζαμπόν, ντομάτα, μπέικον και μαρούλι.", price: "€8.00" },
      { name: "Chicken Club Sandwich", description: "Club sandwich με τρυφερό κοτόπουλο, τυρί, ντομάτα και μαρούλι.", price: "€9.00" },
      { name: "Cheeseburger", description: "Ζουμερό μπιφτέκι με λιωμένο τυρί και τη σάλτσα μας.", price: "€9.00" },
      { name: "Chicken Burger", description: "Burger κοτόπουλο με τυρί, φρέσκια ντομάτα, μαρούλι και σάλτσα μουστάρδας.", price: "€9.00" },
      { name: "Burger με Καραμελωμένα Κρεμμύδια", description: "Burger με γλυκά καραμελωμένα κρεμμύδια, ντομάτα και μαρούλι.", price: "€9.50" },
    ],
    "Salads": [
      { name: "Χωριάτικη Σαλάτα", description: "Κλασική χωριάτικη με ντομάτα, αγγούρι, ελιές, πιπεριά και φέτα.", price: "€8.50" },
      { name: "Σαλάτα του Καίσαρα", description: "Πράσινη σαλάτα, μπέικον, κρουτόν, κοτόπουλο και dressing Caesar's.", price: "€9.00" },
      { name: "Σαλάτα Ρόκα", description: "Φύλλα ρόκας με παρμεζάνα και απλή σάλτσα βαλσάμικο.", price: "€9.00" },
      { name: "Σαλάτα Soleto", description: "Η σπεσιαλιτέ μας με φρέσκα λαχανικά, πορτοκάλι, σταφίδες, καρύδια, παρμεζάνα και κρέμα βαλσάμικο.", price: "€9.00" },
    ],
    "Appetizers": [
      { name: "Φέτα", description: "Κλασική ελληνική φέτα με ελαιόλαδο και ρίγανη.", price: "€4.50" },
      { name: "Τυροκαυτερή", description: "Κρεμώδης και πικάντικη αλοιφή τυριού.", price: "€5.00" },
      { name: "Σαγανάκι", description: "Τηγανητό τυρί με χρυσή κρούστα.", price: "€5.50" },
      { name: "Ταλαγάνι", description: "Ψητό τυρί Ταλαγάνι, μαλακό με ξεχωριστή γεύση.", price: "€6.00" },
      { name: "Φέτα με Μέλι", description: "Ψητή φέτα με μέλι και σουσάμι.", price: "€6.50" },
      { name: "Πατάτες Τηγανητές", description: "Τραγανές, χρυσές πατάτες.", price: "€4.00" },
      { name: "Γαύρος Μαρινάτος", description: "Φιλέτα γαύρου μαριναρισμένα σε ελαιόλαδο και μυρωδικά.", price: "€8.00" },
      { name: "Γαύρος Τηγανητός", description: "Τραγανός γαύρος, το τέλειο σνακ για την παραλία.", price: "€8.50" },
      { name: "Καλαμαράκια Τηγανητά", description: "Τρυφερά καλαμαράκια, σερβίρονται με aioli λεμονιού και ρόκα.", price: "€10.00" },
    ],
    "Pizza": [
      { name: "Pizza Margarita", description: "Κλασική με σάλτσα ντομάτας και τυρί γκούντα.", price: "€9.50" },
      { name: "Pizza Ham", description: "Με σάλτσα ντομάτας, ζαμπόν και τυρί γκούντα.", price: "€11.00" },
      { name: "Pizza Peperone", description: "Πικάντικη με σάλτσα ντομάτας, πεπερόνι και τυρί γκούντα.", price: "€12.00" },
      { name: "Pizza Classic", description: "Με σάλτσα ντομάτας, μπέικον, ζαμπόν και τυρί γκούντα.", price: "€12.00" },
      { name: "Pizza Greek", description: "Ελληνική γεύση με σάλτσα, γκούντα, ελιές, πιπεριά, φρέσκια ντομάτα, κρεμμύδι και φέτα.", price: "€13.00" },
      { name: "Pizza Special", description: "Πλούσια με σάλτσα, μπέικον, ζαμπόν, γκούντα, πιπεριά και μανιτάρια.", price: "€13.00" },
    ],
    "Pasta": [
      { name: "Pomodoro", description: "Απλή και νόστιμη με σάλτσα ντομάτας, φρέσκο βασιλικό και Κεφαλοτύρι.", price: "€8.50" },
      { name: "Carbonara", description: "Κρεμώδης κλασική με μπέικον, κρέμα γάλακτος και παρμεζάνα.", price: "€9.50" },
      { name: "Ζυμαρικά Φούρνου", description: "Στο φούρνο με γκούντα, ζαμπόν, μπέικον, σάλτσα ντομάτας και βασιλικό.", price: "€9.50" },
      { name: "Πέννες All Freddo με Κοτόπουλο", description: "Πέννες σε κρεμώδη σάλτσα με κοτόπουλο, παρμεζάνα και λίγη κρέμα γάλακτος.", price: "€10.00" },
    ],
    "Grill": [
      { name: "Λουκάνικο", description: "Χωριάτικο λουκάνικο σχάρας.", price: "€7.50" },
      { name: "Πανσέτα", description: "Χοιρινή πανσέτα ψητή.", price: "€9.50" },
      { name: "Φιλέτο Κοτόπουλο", description: "Τρυφερό φιλέτο κοτόπουλο σχάρας.", price: "€10.50" },
      { name: "Μπιφτέκι Μοσχαρίσιο με Πατάτες", description: "Κλασικό μπιφτέκι με τραγανές πατάτες τηγανητές.", price: "€10.50" },
      { name: "Χοιρινή Μπριζόλα με Πατάτες", description: "Ζουμερή χοιρινή μπριζόλα με πατάτες τηγανητές.", price: "€12.00" },
      { name: "Mix Grill (2 άτομα)", description: "Ποικιλία με μπριζόλα, μπιφτέκι, κοτόπουλο, λουκάνικο, πανσέτα, πατάτες και πίτα.", price: "€29.50" },
      { name: "Mix Grill (4 άτομα)", description: "Μεγάλη ποικιλία κρεατικών για την παρέα.", price: "€39.50" },
      { name: "Ποικιλία Θαλασσινών (2 άτομα)", description: "Γαύρος, μπακαλιάρος, γαύρος μαρινάτος, γαρίδες, καλαμαράκια και χταπόδι.", price: "€35.00" },
      { name: "Ποικιλία Θαλασσινών (4 άτομα)", description: "Μεγάλη ποικιλία θαλασσινών.", price: "€50.00" },
    ],
    "Sweets": [
      { name: "Μπάλα Παγωτού", description: "Μια μπάλα από το αγαπημένο σας παγωτό, με σιρόπι.", price: "€2.50" },
      { name: "Φρουτοσαλάτα", description: "Δροσερή φρουτοσαλάτα με φρέσκα φρούτα εποχής.", price: "€8.00" },
      { name: "Γιαούρτι με Μέλι και Καρύδια", description: "Κρεμώδες ελληνικό γιαούρτι με μέλι και τραγανά καρύδια.", price: "€5.00" },
      { name: "Κρέπα Σοκολάτα", description: "Λεπτή κρέπα γεμισμένη με πλούσια σοκολάτα. Προσθέστε τα αγαπημένα σας υλικά.", price: "€4.50" },
      { name: "Βάφλα με Σοκολάτα", description: "Ζεστή βάφλα με πλούσια σάλτσα σοκολάτας. Προσθέστε παγωτό για την τέλεια απόλαυση.", price: "€5.00" },
      { name: "Pancakes με Πραλίνα | Bueno | Μέλι", description: "Αφράτα pancakes με επιλογή από πραλίνα, Bueno ή μέλι.", price: "€5.00" },
    ],
    "Wines": [
      { name: "Λευκό Κρασί Χύμα Ποτήρι", description: "", price: "€3.50" },
      { name: "Λευκό Κρασί Χύμα 500ml", description: "", price: "€6.00" },
      { name: "Κόκκινο Κρασί Χύμα Ποτήρι", description: "", price: "€3.50" },
      { name: "Κόκκινο Κρασί Χύμα 500ml", description: "", price: "€6.00" },
      { name: "Κρασί Εμφιαλωμένο Ατομικό", description: "", price: "€4.00" },
      { name: "Ροδίτης Τετράμυθος Nature", description: "", price: "€15.00" },
      { name: "Μαλαγουζιά Τετράμυθος Nature", description: "", price: "€19.00" },
      { name: "Kintonis Checkmate Semi Sweet White", description: "", price: "€14.00" },
      { name: "Αγιωργίτικο Τετράμυθος Nature", description: "", price: "€17.00" },
    ],
    "Alcohol and beers": [
      { name: "ALFA | ALFA FREE", description: "", price: "€4.00" },
      { name: "BEER ALFA 330ml", description: "", price: "€4.00" },
      { name: "BEER ALFA 500ml", description: "", price: "€4.50" },
      { name: "AMSTEL", description: "", price: "€4.00" },
      { name: "FIX", description: "", price: "€4.00" },
      { name: "MAMMOS", description: "", price: "€4.00" },
      { name: "HEINEKEN", description: "", price: "€4.50" },
      { name: "FISCHER", description: "", price: "€4.50" },
      { name: "KAIZER", description: "", price: "€4.50" },
      { name: "SOL", description: "", price: "€4.50" },
      { name: "RADLER", description: "", price: "€4.50" },
      { name: "APPLE CIDER", description: "", price: "€4.50" },
      { name: "Ούζο | Τσίπουρο Μεζέ (ψάρι | κρέας)", description: "", price: "€5.00" },
      { name: "Ούζο | Τσίπουρο εμφιαλωμένο 50ml με μεζέ", description: "", price: "€5.50" },
      { name: "Ούζο 250ml", description: "", price: "€7.50" },
      { name: "Τσίπουρο 250ml", description: "", price: "€7.00" },
      { name: "VODKA", description: "", price: "€6.50" },
      { name: "GIN", description: "", price: "€6.50" },
      { name: "TEQUILA", description: "", price: "€6.50" },
      { name: "BACARDI", description: "", price: "€6.50" },
      { name: "MALIBU", description: "", price: "€8.00" },
      { name: "SCOTCH", description: "", price: "€6.50" },
      { name: "SPECIAL SCOTCH", description: "", price: "€8.00" },
      { name: "CAMPARI", description: "", price: "€6.50" },
      { name: "APEROL", description: "", price: "€7.00" },
      { name: "MARTINI", description: "", price: "€6.50" },
      { name: "MOJITO", description: "", price: "€6.50" },
      { name: "SANGRIA", description: "", price: "€6.00" },
      { name: "MOSCATO D'ASTI", description: "", price: "€6.00" },
      { name: "GORDON'S SPACE", description: "", price: "€5.00" },
      { name: "BACARDI BREEZER (καρπούζι | λεμόνι)", description: "", price: "€3.00" },
      { name: "MASTIC LIQUEUR (σφηνάκι)", description: "", price: "€8.00" },
    ],
  }
};

export const menuCategories = {
  en: [
    "All", "Coffee", "Beverages", "Breakfast", "Snacks", "Salads", "Appetizers",
    "Pizza", "Pasta", "Grill", "Sweets", "Wines", "Alcohol and beers"
  ],
  el: [
    "Όλα", "Καφές", "Ροφήματα", "Πρωινό", "Σνακ", "Σαλάτες", "Ορεκτικά",
    "Πίτσα", "Ζυμαρικά", "Της Ώρας", "Γλυκά", "Κρασιά", "Ποτά"
  ]
};